---
kibana_version: "7.x"

kibana_package: kibana
kibana_package_state: present

kibana_service_state: started
kibana_service_enabled: true

kibana_config_template: kibana.yml.j2
kibana_config_file_path: /etc/kibana/kibana.yml

kibana_server_port: 5601
kibana_server_host: "0.0.0.0"

# roles/k/defaults/main.yml
kibana_elasticsearch_url: "https://localhost:9200"

# # Kibana internal user (not elastic)
# kibana_elasticsearch_username: "kibana_system"
# kibana_elasticsearch_password: "SOME_LONG_PASSWORD"


# kibana_elasticsearch_url: "http://localhost:9200"
# kibana_elasticsearch_username: ""
# kibana_elasticsearch_password: ""
# k_es_password: "{{ es_bootstrap_password }}"

#elasticsearch.hosts: ["https://localhost:9200"]

elasticsearch.username: "{{ kibana_elasticsearch_username }}"
elasticsearch.password: "{{ kibana_elasticsearch_password }}"

# elasticsearch.ssl.certificateAuthorities: ["/etc/elasticsearch/certs/http_ca.crt"]
# elasticsearch.ssl.verificationMode: certificate    # or "none" in lab