---
- name: Install Elasticsearch 8.x on Ubuntu
  hosts: es

  become: true
  vars:
    es_bootstrap_password: "{{ es_bootstrap_password }}"   # choose and keep
    kibana_system_password: "{{ es_bootstrap_password }}"
  roles:
    - es
    - ls
    - k
